gateware.platform.ecpix5: comment out unused serdes pins to avoid nextpnr error
If the pins are referenced but not actually used in the design, nextpnr will throw an error like this:

   ERROR: IO pin 'serdes_0__refclk__p$tr_io' constrained to pin 'AF12', which does not exist for package 'CABGA554'